name = "elementbau-nienburg-backend"
main = "src/index.js"
compatibility_date = "2024-05-23"

[vars]
RESEND_API_KEY = "REPLACE_WITH_YOUR_RESEND_API_KEY"
CLOUDFLARE_TURNSTILE_SECRET_KEY = "REPLACE_WITH_YOUR_TURNSTILE_SECRET"
